// https://code.tutsplus.com/articles/an-introduction-to-mongoose-for-mongodb-and-nodejs--cms-29527
const mongoose = require('mongoose');
let subSubscriptonSchema = mongoose.Schema({
  _id: Number,
  address_id: Number,
  cancellation_reason: String,
  cancellation_reason_comments: String,
  cancelled_at: Date,
  charge_interval_frequency: String,
  created_at: Date,
  customer_id: Number,
  expire_after_specific_number_of_charges: Number,
  has_queued_charges: Number,
  is_skippable: Boolean,
  is_swappable: Boolean,
  max_retries_reached: Number,
  next_charge_scheduled_at: Date,
  order_day_of_month: Number,
  order_day_of_week: Number,
  order_interval_frequency: String,
  order_interval_unit: String,
  price: Number,
  product_title: String,
  properties: [],
  quantity: Number,
  recharge_product_id: Number,
  shopify_product_id: Number,
  shopify_variant_id: Number,
  sku: String,
  sku_override: Boolean,
  status: String,
  updated_at: Date,
  variant_title: String
});
let subscriptonSchema = mongoose.Schema({
  _id: Number,
  address_id: Number,
  cancellation_reason: String,
  cancellation_reason_comments: String,
  cancelled_at: Date,
  charge_interval_frequency: String,
  created_at: Date,
  customer_id: Number,
  expire_after_specific_number_of_charges: Number,
  has_queued_charges: Number,
  is_skippable: Boolean,
  is_swappable: Boolean,
  max_retries_reached: Number,
  next_charge_scheduled_at: Date,
  order_day_of_month: Number,
  order_day_of_week: Number,
  order_interval_frequency: String,
  order_interval_unit: String,
  price: Number,
  product_title: String,
  properties: [],
  quantity: Number,
  recharge_product_id: Number,
  shopify_product_id: Number,
  shopify_variant_id: Number,
  sku: String,
  sku_override: Boolean,
  status: String,
  updated_at: Date,
  variant_title: String,
  orders: [String],
  versions: [subSubscriptonSchema]
});
let Subscription = mongoose.model('Subscription', subscriptonSchema);
module.exports = Subscription;
